import { Smooch_Sans } from 'next/font/google';
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import NavigationBar from '@/components/layouts/NavigationBar';
import 'swiper/swiper-bundle.css';
import Footer from '@/components/layouts/Footer';
import 'react-circular-progressbar/dist/styles.css';
import 'aos/dist/aos.css'; 


const smoochSans = Smooch_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-smooch-sans",
});

export const metadata = {
  title: "UNILabs",
  description: "Generated by UNILabs",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`m-0 ${smoochSans.variable}`}>
        <NavigationBar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
